import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/ui/custom/header";

const oswald = Oswald({ subsets: ["latin"],variable: "--font-oswald" });

export const metadata: Metadata = {
  title: "Grocery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn( 
        "min-h-screen bg-background font-oswald antialiased",
          oswald.variable
        )}>
          
          <Header/>
          <main>{children}</main>
          </body>
    </html>
  );
}
